import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const FAQS: { question: string; answer: string }[] = [
  {
    question: "What is AI answer engine visibility?",
    answer:
      "It is how often, and how favorably, your brand surfaces inside answers generated by tools like ChatGPT, Claude, Perplexity, and Gemini. Unlike classic SEO, there are no blue links — your brand either gets cited in the synthesized answer, or it does not.",
  },
  {
    question: "Which AI engines does Sitebench track?",
    answer:
      "We continuously monitor ChatGPT, Claude, Gemini, Perplexity, and Grok across the prompts you care about. New engines are rolled into your workspace automatically as they hit meaningful usage — no migration work required.",
  },
  {
    question: "How are prompts selected and refreshed?",
    answer:
      "During onboarding we generate a starter set of prompts from your site, category, and competitors. You can add, edit, or retire prompts at any time, and we re-run the full set on a scheduled cadence so your dashboards always reflect the current state of the answer layer.",
  },
  {
    question: "Can I compare my brand against competitors?",
    answer:
      "Yes. Every metric — visibility, ranking, sentiment, citation share — is available per competitor, per engine, per prompt. You can pin a peer set on your dashboard and track how your position shifts week over week.",
  },
  {
    question: "How is this different from traditional SEO tools?",
    answer:
      "Classic SEO tools measure rank on a search results page. Sitebench measures whether the generative layer — the thing that increasingly replaces that page — recommends you, in what context, and with what tone. The two are complementary, not interchangeable.",
  },
  {
    question: "Do you offer a free trial?",
    answer:
      "Every new workspace starts with a free trial that includes your full prompt library, all major engines, and competitor benchmarking. No credit card is required to begin, and you keep all dashboards you configure during the trial.",
  },
]

export function FaqSection() {
  return (
    <section
      id="faq"
      className="relative mx-auto w-full max-w-5xl scroll-mt-24 px-4 pt-16 pb-20 sm:pt-20 md:pt-24"
    >
      <div className="grid gap-10 md:grid-cols-12 md:gap-12">
        <header className="md:col-span-5 md:sticky md:top-24 md:self-start">
          <h2 className="font-heading text-balance text-3xl leading-[1.05] tracking-[-0.02em] text-foreground sm:text-4xl md:text-[2.75rem]">
            Questions,
            <br />
            answered.
          </h2>
          <p className="mt-4 max-w-sm text-sm leading-relaxed text-pretty text-muted-foreground sm:text-base">
            Everything teams ask before putting Sitebench in front of their
            marketing and product leaders. Still curious? Reach us at{" "}
            <a
              href="mailto:hello@sitebench.ai"
              className="text-foreground underline-offset-4 hover:underline"
            >
              hello@sitebench.ai
            </a>
            .
          </p>
        </header>

        <div className="relative md:col-span-7">
          <div className="relative border border-border bg-card">
            <Accordion type="single" collapsible className="w-full">
              {FAQS.map((faq, index) => (
                <AccordionItem
                  key={faq.question}
                  value={`faq-${index}`}
                  className="border-b border-border last:border-b-0"
                >
                  <AccordionTrigger className="group/faq-row items-center gap-4 px-5 py-4 text-sm font-medium hover:no-underline sm:px-6 sm:py-5 sm:text-[0.95rem]">
                    <span
                      aria-hidden="true"
                      className="font-mono text-[10px] tabular-nums text-muted-foreground transition-colors group-hover/faq-row:text-foreground group-aria-expanded/faq-row:text-foreground"
                    >
                      {String(index + 1).padStart(2, "0")}
                    </span>
                    <span className="flex-1 text-balance text-left text-foreground">
                      {faq.question}
                    </span>
                  </AccordionTrigger>
                  <AccordionContent className="px-5 pb-5 text-sm leading-relaxed text-pretty text-muted-foreground sm:px-6 sm:pb-6 sm:text-[0.9rem]">
                    <div className="pl-0 sm:pl-8">{faq.answer}</div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </div>
      </div>
    </section>
  )
}

