-- Canonical schema artifact moved to:
-- db/migrations/0001_brand_intelligence.sql
--
-- This compatibility file remains in place so older references do not silently
-- point at the removed onboarding-only schema.
